[project]
name = "ms2x"
version = "0.1.1"
requires-python = ">=3.10"

dependencies = [
    "matchms>=0.26,<0.34",
    "numpy>=2.0",
    "rdkit>=2024.3.5,<2025.0.0",
    "tqdm>=4.65.0",
]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
include = ["ms2x*"]